services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - purify-network
    volumes:
      - type: bind
        source: ${LOG_DIRECTORY}
        target: /var/log/purify

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ${REDIS_DATA_DIRECTORY}:/data
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    ports:
      - "6379:6379"
    networks:
      - purify-network

networks:
  purify-network:
    name: purify-network
    driver: bridge
