model_path:
  "final_model.pth"

model_cigarette_detection_path:
  "weights.pt"

num_classes:
  6

class_names:
  ["dick", "drawings", "hentai", "neutral", "porn", "sexy"]

probabilty_threshold:
  0.82

detection_threshold:
  0.3

roboflow_model:
  "smoke-detector-bb0pv/1"
