main:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  read_header_timeout: 10s
  idle_timeout: 30s
  shutdown_timeout: 10s
mistral_ai:
  base_url: https://api.mistral.ai
  completions_url: /v1/chat/completions