main:
  port: 8080
  read_timeout: 120s
  write_timeout: 120s
  read_header_timeout: 120s
  idle_timeout: 120s
  shutdown_timeout: 10s
mistral_ai:
  base_url: https://api.mistral.ai
  completions_url: /v1/chat/completions
  words_in_chunk: 20
  max_chunks: 2
chat_gpt:
  base_url: https://api.openai.com
  completions_url: /v1/chat/completions
  model: gpt-4o-mini
  words_in_chunk: 30 # for blur
  max_chunks: 100 # for blur
  max_tokens_in_chunk: 500 # for replace
  simplify_min_tokens_in_chunk: 100
  simplify_max_tokens_in_chunk: 1000
deepseek:
  base_url: https://api.deepseek.com
  completions_url: /chat/completions
  model: deepseek-chat
  words_in_chunk: 30 # for blur
  max_chunks: 100 # for blur
  max_tokens_in_chunk: 500 # for replace
  simplify_min_tokens_in_chunk: 100
  simplify_max_tokens_in_chunk: 1000
minio:
  bucket_name: purify
easy_ocr:
  host: easy_ocr
  port: 5002
  endpoint: process_image
  endpoint_parallel: process_images_batch
